######################################################################
# Automatically generated by qmake (3.1) Tue Sep 19 16:50:22 2017
######################################################################
TEMPLATE = subdirs
CONFIG+=ordered

SUBDIRS = \
    src \
    tests

OTHER_FILES += \
    defaults.pri

tests.depends = src
